In [31]:
import numpy as np
import pandas as pd

In [33]:
new = np.array([2,3,4,5,6])
new

array([2, 3, 4, 5, 6])

In [34]:
a = np.random.rand(3,4)
a

array([[0.36659058, 0.91538858, 0.01806359, 0.82602122],
       [0.99927502, 0.80818931, 0.06605372, 0.65889613],
       [0.85968993, 0.81926407, 0.2531843 , 0.56088329]])

In [56]:
a.reshape(12,1).transpose()

array([[0.36659058, 0.91538858, 0.01806359, 0.82602122, 0.99927502,
        0.80818931, 0.06605372, 0.65889613, 0.85968993, 0.81926407,
        0.2531843 , 0.56088329]])

In [48]:
b = np.random.rand(1,4)
b

array([[0.08195455, 0.15049809, 0.54267322, 0.60380865]])

In [46]:
np.concatenate((a,b1), axis=1)

array([[0.36659058, 0.91538858, 0.01806359, 0.82602122, 0.1536799 ],
       [0.99927502, 0.80818931, 0.06605372, 0.65889613, 0.10518476],
       [0.85968993, 0.81926407, 0.2531843 , 0.56088329, 0.27281637]])

In [47]:
b1 = np.random.rand(3,1)
b1

array([[0.11277371],
       [0.07399972],
       [0.45361585]])

In [49]:
c= b.transpose()
c

array([[0.08195455],
       [0.15049809],
       [0.54267322],
       [0.60380865]])

In [51]:
c.shape

(4, 1)

In [52]:
a

array([[0.36659058, 0.91538858, 0.01806359, 0.82602122],
       [0.99927502, 0.80818931, 0.06605372, 0.65889613],
       [0.85968993, 0.81926407, 0.2531843 , 0.56088329]])

In [53]:
a.transpose()

array([[0.36659058, 0.99927502, 0.85968993],
       [0.91538858, 0.80818931, 0.81926407],
       [0.01806359, 0.06605372, 0.2531843 ],
       [0.82602122, 0.65889613, 0.56088329]])

In [54]:
range1 = np.arange(0,10)
range1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
range2 = np.arange(0,1, 0.2)
range2

array([0. , 0.2, 0.4, 0.6, 0.8])

In [59]:
line = np.linspace(0,1,5)
line

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
line

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])