# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [7]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
np.concatenate((mat2, mat3.T))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [10]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [11]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [12]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [13]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.80492111 0.36797075 0.30454216 0.72857373 0.61675315]
 [0.73745118 0.88746088 0.49457808 0.61016367 0.51746651]
 [0.21770326 0.96745226 0.85883849 0.53430592 0.10186307]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]

[[-1.23288175 -0.88813909 -0.15640249 -1.52648519  0.34149243]
 [ 1.38881546  1.41437848 -0.52692725 -1.10135084 -0.32878499]
 [-0.35780069  0.45382081  0.89076643  1.00723039  1.49054166]
 [-0.93790428  0.03347393 -0.5905212   0.55880802 -1.35258311]
 [ 1.0197918  -2.20767839  0.7133552  -0.51617895 -0.3920353 ]
 [ 1.99011056 -0.62066468 -0.1313068   1.62890109  0.89628255]
 [ 0.17299455 -0.71902342 -1.11272084 -0.95719911  0.72882878]
 [-1.38742385  0.95433115  0.95782904 -0.87222722  0.69144253]
 [-0.21448362  1.9335935  -0.97196488 -1.12353414 -0.12920349]
 [-0.38002302 -1.00874968 -0.11493089 -0.07071608  0.29310205]]


In [14]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5250919325480013
0.9807365712583734


In [15]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.05783301577096056
1.9901105566665744


In [16]:
# break here for next video!

In [17]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.28840282  1.60605651  0.01297824 -0.3135444   1.23062157 -1.6158883
  0.50472899 -1.46570051  0.10968463 -0.06386618 -0.2716062  -0.77420309
  0.70975973 -0.65095715  0.68226233 -0.43233048  0.9832627  -0.6499543
 -1.17494605]
0.5047289940173099


In [18]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.23062157 -1.6158883   0.50472899 -1.46570051  0.10968463]


In [19]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.28840282 -0.3135444   0.50472899 -0.06386618  0.70975973]


In [20]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.80492111 0.36797075 0.30454216 0.72857373 0.61675315]
 [0.73745118 0.88746088 0.49457808 0.61016367 0.51746651]
 [0.21770326 0.96745226 0.85883849 0.53430592 0.10186307]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]
0.49457807702939927
0.49457807702939927


In [21]:
print(rand_mat[0:2,1:3])

[[0.36797075 0.30454216]
 [0.88746088 0.49457808]]


In [22]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.28840282  1.60605651  0.01297824 -0.3135444   1.23062157 -1.6158883
  0.50472899 -1.46570051  0.10968463 -0.06386618 -0.2716062  -0.77420309
  0.70975973 -0.65095715  0.68226233 -0.43233048  0.9832627  -0.6499543
 -1.17494605]

[ 1.28840282  1.60605651  0.01297824  4.          4.         -1.6158883
  0.50472899 -1.46570051  0.10968463 -0.06386618 -0.2716062  -0.77420309
  0.70975973 -0.65095715  0.68226233 -0.43233048  0.9832627  -0.6499543
 -1.17494605]

[ 1.28840282  1.60605651  0.01297824  1.          2.         -1.6158883
  0.50472899 -1.46570051  0.10968463 -0.06386618 -0.2716062  -0.77420309
  0.70975973 -0.65095715  0.68226233 -0.43233048  0.9832627  -0.6499543
 -1.17494605]


In [23]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.80492111 0.36797075 0.30454216 0.72857373 0.61675315]
 [0.73745118 0.88746088 0.49457808 0.61016367 0.51746651]
 [0.21770326 0.96745226 0.85883849 0.53430592 0.10186307]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]

[[0.80492111 0.36797075 0.30454216 0.72857373 0.61675315]
 [0.73745118 0.88746088 0.49457808 0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]


In [24]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.80492111 0.36797075 0.30454216]
 [0.73745118 0.88746088 0.49457808]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [25]:
print(rand_mat)

[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.         3.         0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]


In [26]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.         3.         0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]


In [ ]:
# break here for next video

In [39]:
rand_mat.flatten().shape

(25,)

In [28]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.23001579  0.68593773 -0.25940209  1.18893708 -0.46306623  2.69345585
  1.46832042 -0.82989946 -1.7964344  -0.38137699  0.2158683  -0.06836579
 -0.16233859  0.90933172  1.29232963]
[False  True False  True False  True  True False False False  True False
 False  True  True]
[0.68593773 1.18893708 2.69345585 1.46832042 0.2158683  0.90933172
 1.29232963]


In [29]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-1.23288175 -0.88813909 -0.15640249 -1.52648519  0.34149243]
 [ 1.38881546  1.41437848 -0.52692725 -1.10135084 -0.32878499]
 [-0.35780069  0.45382081  0.89076643  1.00723039  1.49054166]
 [-0.93790428  0.03347393 -0.5905212   0.55880802 -1.35258311]
 [ 1.0197918  -2.20767839  0.7133552  -0.51617895 -0.3920353 ]
 [ 1.99011056 -0.62066468 -0.1313068   1.62890109  0.89628255]
 [ 0.17299455 -0.71902342 -1.11272084 -0.95719911  0.72882878]
 [-1.38742385  0.95433115  0.95782904 -0.87222722  0.69144253]
 [-0.21448362  1.9335935  -0.97196488 -1.12353414 -0.12920349]
 [-0.38002302 -1.00874968 -0.11493089 -0.07071608  0.29310205]]
[0.34149243 1.38881546 1.41437848 0.45382081 0.89076643 1.00723039
 1.49054166 0.03347393 0.55880802 1.0197918  0.7133552  1.99011056
 1.62890109 0.89628255 0.17299455 0.72882878 0.95433115 0.95782904
 0.69144253 1.9335935  0.29310205]


In [30]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.23001579  0.68593773 -0.25940209  1.18893708 -0.46306623  2.69345585
  1.46832042 -0.82989946 -1.7964344  -0.38137699  0.2158683  -0.06836579
 -0.16233859  0.90933172  1.29232963]

[-0.23001579 -5.         -0.25940209 -5.         -0.46306623 -5.
 -5.         -0.82989946 -1.7964344  -0.38137699  0.2158683  -0.06836579
 -0.16233859 -5.         -5.        ]


In [31]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [32]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [33]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.23288175 -0.88813909 -0.15640249 -1.52648519  0.34149243]
 [ 1.38881546  1.41437848 -0.52692725 -1.10135084 -0.32878499]
 [-0.35780069  0.45382081  0.89076643  1.00723039  1.49054166]
 [-0.93790428  0.03347393 -0.5905212   0.55880802 -1.35258311]
 [ 1.0197918  -2.20767839  0.7133552  -0.51617895 -0.3920353 ]
 [ 1.99011056 -0.62066468 -0.1313068   1.62890109  0.89628255]
 [ 0.17299455 -0.71902342 -1.11272084 -0.95719911  0.72882878]
 [-1.38742385  0.95433115  0.95782904 -0.87222722  0.69144253]
 [-0.21448362  1.9335935  -0.97196488 -1.12353414 -0.12920349]
 [-0.38002302 -1.00874968 -0.11493089 -0.07071608  0.29310205]]



In [34]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.         3.         0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]

[[-1.23288175 -0.88813909 -0.15640249 -1.52648519  0.34149243]
 [ 1.38881546  1.41437848 -0.52692725 -1.10135084 -0.32878499]
 [-0.35780069  0.45382081  0.89076643  1.00723039  1.49054166]
 [-0.93790428  0.03347393 -0.5905212   0.55880802 -1.35258311]
 [ 1.0197918  -2.20767839  0.7133552  -0.51617895 -0.3920353 ]
 [ 1.99011056 -0.62066468 -0.1313068   1.62890109  0.89628255]
 [ 0.17299455 -0.71902342 -1.11272084 -0.95719911  0.72882878]
 [-1.38742385  0.95433115  0.95782904 -0.87222722  0.69144253]
 [-0.21448362  1.9335935  -0.97196488 -1.12353414 -0.12920349]
 [-0.38002302 -1.00874968 -0.11493089 -0.07071608  0.29310205]]
[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.    

In [35]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.         3.         0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]

[[3.         3.         3.         0.72857373 0.61675315]
 [3.         3.         3.         0.         0.        ]
 [0.21770326 0.96745226 0.85883849 0.         0.        ]
 [0.16502866 0.41187234 0.35931353 0.05783302 0.65701601]
 [0.49157536 0.73277707 0.52895365 0.16755481 0.80532964]]
